schema = 3

[mod]
  [mod.'code.linenisgreat.com/dodder/go']
    version = 'v0.0.0-20260208160524-0a77d5e62729'
    hash = 'sha256-8TjINgryiOcsx+6OtW7fc0zPU5LgnGwPxW98oc+eX74='

  [mod.'filippo.io/age']
    version = 'v1.3.1'
    hash = 'sha256-Qs/q3zQYV0PukABBPf/aU5V1oOhw95NG6K301VYJk8A='

  [mod.'filippo.io/hpke']
    version = 'v0.4.0'
    hash = 'sha256-xKPT2hMzz/i3xdDK3NKn6FOmfQPxIMgxCOmm8U1heY4='

  [mod.'github.com/brandondube/tai']
    version = 'v0.1.0'
    hash = 'sha256-o32wvMW6waT/vJJkpjiCGxBNBUsqeAvnARhbsikRk50='

  [mod.'github.com/google/go-cmp']
    version = 'v0.7.0'
    hash = 'sha256-JbxZFBFGCh/Rj5XZ1vG94V2x7c18L8XKB0N9ZD5F2rM='

  [mod.'github.com/google/jsonschema-go']
    version = 'v0.4.2'
    hash = 'sha256-kNExU/AI+CS27tQntXEpFqSio+HV2wzo2P458jqncOk='

  [mod.'github.com/modelcontextprotocol/go-sdk']
    version = 'v1.2.0'
    hash = 'sha256-eZJr7ru3v3l3t46EhLYW7TuGqWFnx172vJA0SIoaOWA='

  [mod.'github.com/yosida95/uritemplate/v3']
    version = 'v3.0.2'
    hash = 'sha256-znUsCrfogPwAUNsdxBL93jIW/joercUm7RxKSExuWTM='

  [mod.'golang.org/x/crypto']
    version = 'v0.47.0'
    hash = 'sha256-78iRvMmPZVTBrIk30yGpAO11kVC5TLR1zGW85gFLHk4='

  [mod.'golang.org/x/exp']
    version = 'v0.0.0-20260112195511-716be5621a96'
    hash = 'sha256-rWqwXzLvvhcI/ZkOQMqCXMKI5FAuHd9YNoKTXujmboA='

  [mod.'golang.org/x/oauth2']
    version = 'v0.35.0'
    hash = 'sha256-QeleoXu+9K3LJZiw6/iPR+EQzi/OLDBTFdrP2/d1XN8='

  [mod.'golang.org/x/sys']
    version = 'v0.40.0'
    hash = 'sha256-KDe+wMr7dfMFwKMJEljzk+f82pQWFFPoFHivjD7qJGg='

  [mod.'golang.org/x/term']
    version = 'v0.39.0'
    hash = 'sha256-diP4VknZDlJmhGQdcsXwI2+sFayQdsILFuxK1FBPaUE='

  [mod.'golang.org/x/xerrors']
    version = 'v0.0.0-20240903120638-7835f813f4da'
    hash = 'sha256-bE7CcrnAvryNvM26ieJGXqbAtuLwHaGcmtVMsVnksqo='
