schema = 3

[mod]
  [mod."code.linenisgreat.com/dodder/go"]
    version = "v0.0.0-20251227143023-45addc7cfae0"
    hash = "sha256-RHzSCozE1Tv4iZOnEOzyeukgkZkr9BS1aa5ulzOTba0="
  [mod."filippo.io/age"]
    version = "v1.2.1"
    hash = "sha256-9ZJdrmqBj43zSvStt0r25wjSfnvitdx3GYtM3urHcaA="
  [mod."github.com/brandondube/tai"]
    version = "v0.1.0"
    hash = "sha256-o32wvMW6waT/vJJkpjiCGxBNBUsqeAvnARhbsikRk50="
  [mod."github.com/google/go-cmp"]
    version = "v0.7.0"
    hash = "sha256-JbxZFBFGCh/Rj5XZ1vG94V2x7c18L8XKB0N9ZD5F2rM="
  [mod."github.com/google/jsonschema-go"]
    version = "v0.3.0"
    hash = "sha256-GIVEtsm2C1nUWa3lOh56Z8dEYS4vRDQeTpiy1mIFXUg="
  [mod."github.com/modelcontextprotocol/go-sdk"]
    version = "v1.2.0"
    hash = "sha256-eZJr7ru3v3l3t46EhLYW7TuGqWFnx172vJA0SIoaOWA="
  [mod."github.com/yosida95/uritemplate/v3"]
    version = "v3.0.2"
    hash = "sha256-znUsCrfogPwAUNsdxBL93jIW/joercUm7RxKSExuWTM="
  [mod."golang.org/x/crypto"]
    version = "v0.46.0"
    hash = "sha256-I8N/spcw3/h0DFA+V1WK38HctckWIB9ep93DEVCALxU="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20251219203646-944ab1f22d93"
    hash = "sha256-0n6AiDMlSiV2jc4+J2RrseVv7oypKO9q1ZUZuaC8wrM="
  [mod."golang.org/x/oauth2"]
    version = "v0.30.0"
    hash = "sha256-btD7BUtQpOswusZY5qIU90uDo38buVrQ0tmmQ8qNHDg="
  [mod."golang.org/x/sys"]
    version = "v0.39.0"
    hash = "sha256-dxTBu/JAWUkPbjFIXXRFdhQWyn+YyEpIC+tWqGo0Y6U="
  [mod."golang.org/x/term"]
    version = "v0.38.0"
    hash = "sha256-46mX91XGJqii6SUESiU5mLVJDBOfKYCp+408m91hrMw="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20240903120638-7835f813f4da"
    hash = "sha256-bE7CcrnAvryNvM26ieJGXqbAtuLwHaGcmtVMsVnksqo="
